name: Build Expo App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Setup Expo CLI
        run: npm install -g eas-cli

      - name: Login to Expo
        if: ${{ secrets.EXPO_TOKEN != '' }}
        run: echo "${{ secrets.EXPO_TOKEN }}" | eas login --non-interactive

      - name: Configure EAS project
        run: |
          # Check if project is already configured
          if ! eas project:info > /dev/null 2>&1; then
            echo "Project not configured, initializing..."
            echo "y" | npx eas init
          fi

      - name: Build Android APK
        run: |
          eas build --profile preview --platform android --non-interactive --wait
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Download build artifact
        run: |
          mkdir -p build
          eas build:download --latest --platform android --output build/
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-apk
          path: build/*.apk

  build-ios:
    if: false  # Disable iOS build for now as it requires macOS runner
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Setup Expo CLI
        run: npm install -g eas-cli

      - name: Login to Expo
        if: ${{ secrets.EXPO_TOKEN != '' }}
        run: echo "${{ secrets.EXPO_TOKEN }}" | eas login --non-interactive

      - name: Configure EAS project
        run: |
          # Check if project is already configured
          if ! eas project:info > /dev/null 2>&1; then
            echo "Project not configured, initializing..."
            echo "y" | npx eas init
          fi

      - name: Build iOS
        run: |
          eas build --profile preview --platform ios --non-interactive --wait
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Download build artifact
        run: |
          mkdir -p build
          eas build:download --latest --platform ios --output build/
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: app-ipa
          path: build/*.ipa